import fs from 'node:fs';
import path from 'node:path';
import { test, after } from 'node:test';
import assert from 'node:assert/strict';

import refactorDesign from '../../.AchillesSkills/gamp/refactor-design/refactor-design.js';
import ignoreFiles from '../../.AchillesSkills/gamp/ignore-files/ignore-files.js';
import GampRSP from '../../GampRSP.mjs';

const TEMP_ROOT = path.join(process.cwd(), 'tests', '.tmp', 'cli-gamp');

// Cleanup temp directories after all tests complete
after(() => {
    if (fs.existsSync(TEMP_ROOT)) {
        fs.rmSync(TEMP_ROOT, { recursive: true, force: true });
    }
});

const makeWorkspace = () => {
    fs.mkdirSync(TEMP_ROOT, { recursive: true });
    const unique = `workspace-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    const target = path.join(TEMP_ROOT, unique);
    fs.mkdirSync(target, { recursive: true });
    return target;
};

const readLines = (filePath) => fs.readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

test('refactor-design creates DS entries and file stubs', { concurrency: false, timeout: 15_000 }, async () => {
    const workspaceRoot = makeWorkspace();
    GampRSP.configure(workspaceRoot);
    const prompt = [
        'Refactor CLI planner to isolate the runner.',
        'Touch src/refactors/plan-runner.mjs and src/config/plan.mjs',
    ].join('\n');

    const outcome = await refactorDesign({
        prompt,
        context: { workspaceRoot },
    });

    assert.ok(Array.isArray(outcome.dsIds) && outcome.dsIds.length === 1, 'Should return a single DS id.');
    const [dsId] = outcome.dsIds;
    const dsFile = GampRSP.getDSFilePath(dsId);
    assert.ok(fs.existsSync(dsFile), `DS file ${dsId} must exist.`);

    const dsContent = fs.readFileSync(dsFile, 'utf8');
    assert.match(dsContent, /src\/refactors\/plan-runner\.mjs/, 'DS should reference plan-runner file.');
    assert.match(dsContent, /src\/config\/plan\.mjs/, 'DS should reference plan config file.');

    const runnerStub = path.join(workspaceRoot, 'src', 'refactors', 'plan-runner.mjs');
    const planStub = path.join(workspaceRoot, 'src', 'config', 'plan.mjs');
    assert.ok(fs.existsSync(runnerStub), 'plan-runner stub should be generated by build-code.');
    assert.ok(fs.existsSync(planStub), 'plan.mjs stub should be generated by build-code.');

    const stubContent = fs.readFileSync(runnerStub, 'utf8');
    assert.match(stubContent, new RegExp(`Managed by ${dsId}`), 'Stub must include DS banner.');
});

test('ignore-files always includes default patterns', { concurrency: false, timeout: 10_000 }, async () => {
    const workspaceRoot = makeWorkspace();
    await ignoreFiles({
        prompt: 'logs, build/output',
        context: { workspaceRoot },
    });

    const ignoreFile = path.join(workspaceRoot, '.specs', '.ignore');
    const entries = readLines(ignoreFile);
    assert.ok(entries.includes('node_modules'), 'Default node_modules entry must be present.');
    assert.ok(entries.includes('logs'), 'Custom entries from the prompt should be captured.');
    assert.ok(entries.includes('build/output'), 'Custom nested paths should be recorded.');
});
